//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        private string name1;
        private string name2;
        private DateTime now1;
        private DateTime now2;

        public Image(string url, string name1, string name2, int id, DateTime now1, DateTime now2)
        {
            this.url = url;
            this.name1 = name1;
            this.name2 = name2;
            this.id = id;
            this.now1 = now1;
            this.now2 = now2;
        }

        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string url { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public Nullable<System.DateTime> updatedAt { get; set; }
        public int Post_id { get; set; }
    
        public virtual Post Post { get; set; }
    }
}
