//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace TravelServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Traveler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Traveler()
        {
            this.Comments = new HashSet<Comment>();
            this.Posts = new HashSet<Post>();
            this.Sub_Comment = new HashSet<Sub_Comment>();
            this.Votes = new HashSet<Vote>();
        }

        public int id { get; set; }
        [StringLength(50, MinimumLength = 5, ErrorMessage = "Ten qua ngan")]
        public string firstName { get; set; }
        [StringLength(50, MinimumLength = 5, ErrorMessage = "Ten qua ngan")]
        public string lastName { get; set; }
        [StringLength(100, MinimumLength = 5, ErrorMessage = "Vui long nhap dia chi")]
        public string address { get; set; }
        [StringLength(11, MinimumLength = 10, ErrorMessage = "Sai so dt")]
        [RegularExpression("([0-9])+", ErrorMessage = "Vui long nhap so")]
        public string phone { get; set; }
        [RegularExpression(@"^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$", ErrorMessage = "Vui long nhap dung dinh dang email")]
        public string email { get; set; }

        public System.DateTime dob { get; set; }
        [StringLength(100, MinimumLength = 8, ErrorMessage = "Pass qua ngan")]
        public string password { get; set; }
        public string salt { get; set; }
        public bool IsEmailVerified { get; set; }
        public System.Guid ActivationCode { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public Nullable<System.DateTime> updatedAt { get; set; }
        public int Role_id { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Post> Posts { get; set; }
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sub_Comment> Sub_Comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vote> Votes { get; set; }
    }
}
